### ISSUE TITLE
Size on Buttons 

### ISSUE THREAD

**Issue by dickermoshe** [nank1ro/shadcn-ui#1]
I understand that this is in the early stages of development, but I had a thought.
Let me know if we should leave you alone during this early phase

Setting the `size` using `ShadcnButtonSize` is ignored if a height is set on the inherited theme.
Arguments on a widget itself should take precedence over the inherited theme.

https://github.com/nank1ro/shadcn-ui/blob/9c3278988be3160d2dbce226b50f7f943a1827f2/lib/src/components/button.dart#L286-L310

P.S. It would be awesome if the preset values could be inherited from the Theme.

**Comment by nank1ro** [comment]
Hi there,
thanks for reporting the issue.
Just refactored the whole theme, because it didn't convince me.
I think how I implemented it now should be better.

I also changed the order in which the operations are performed to compute the size of the button, check
https://github.com/nank1ro/shadcn-ui/blob/main/lib/src/components/button.dart#L298C3-L307C6

I also moved some of the presets in the component theme.
Let me know what you think about it

**Comment by dickermoshe** [comment]
Setting `padding` on the button theme won't work unless the user explicitly sets the theme `size` to `null`.
IMO I would expect an explicitly declared `padding` theme to take precedence over a default `size`.

```dart
EdgeInsets padding(ShadcnThemeData theme) { 
   if (widget.padding != null) return widget.padding!; 
   if (size(theme) != null) {  // <<< This by default will return true
     return defaultPaddingForSize(size(theme)!); // <<< Will be used instead of the themes padding
   } 
   if (buttonTheme(theme).padding != null) {
     return buttonTheme(theme).padding!; 
   } 
   return defaultPaddingForSize(ShadcnButtonSize.$default); 
 } 
```
This is because by default the `size` is set to `$default` and the button uses the `padding` from `size` before the padding theme.
I would make a class to contains presets for each of the button sizes or change default size to `null`

**Comment by dickermoshe** [comment]
I would go with whatever Material Mike has to say about implementing a `ThemeData`, he's done this the most.
Thanks for being so gracious ❤️

**Comment by nank1ro** [comment]
Would you still have the single properties `width`, `height` and `padding` in the Button class?
These properties would be removed from the button theme and converted in this single class?

Feel free to open a PR if you have all in mind 💙
I personally don't like to have multiple sources of truth, for example the `padding` property is determined by both the `padding` and `size` properties, while it should be based on a single source of truth.

**Comment by dickermoshe** [comment]
> Would you still have the single properties width, height and padding in the Button class?
Yeah, using another class would here would seem strange.

>These properties would be removed from the button theme and converted in this single class?
Yup

See what I did here:
https://github.com/nank1ro/shadcn-ui/pull/2

**Comment by dickermoshe** [comment]
Right now the `size` property only affects `width`, `height` and `padding`., so that's what I moved into another class.
I could see how people would want to move other things into a subclass:
E.G. If a user want to have more rounded corners on a large button.

Another way could be having the entire main theme contain 4 different button themes.
This would make things much more complex, we would basically need to do what you've done with the types of buttons (primary, destructive...) for sizes too.

**Comment by nank1ro** [comment]
closed by https://github.com/nank1ro/shadcn-ui/pull/2
