### ISSUE TITLE
Form or FormFields

### ISSUE THREAD

**Issue by nank1ro** [nank1ro/shadcn-ui#23]
https://ui.shadcn.com/docs/components/form

**Comment by dickermoshe** [comment]
Do you plan on baking in validation like shadcn?

**Comment by nank1ro** [comment]
@dickermoshe shadcn uses zod, there is no such equivalent that I know of in dart.
I think I will leave the validation completely up to the user, like Material's form fields.
If you have any suggestions, I'm happy to hear them. Improvements are welcome, for an early version I think we can delegate validation to the user.

**Comment by hamza-imran75** [comment]
There are two libraries similar to Zod:

[Luther](https://pub.dev/packages/luthor)

[Zod](https://pub.dev/packages/zod_validation)

**Comment by nank1ro** [comment]
@hamza-imran75 will check them out, but as I said previously, I'm not going to implement them in the first version. But I'm happy to introduce them in future versions
