### ISSUE TITLE
Add missing `ColorScheme`s

### ISSUE THREAD

**Issue by nank1ro** [nank1ro/shadcn-ui#6]
I already implemented the `zinc` and `slate` color schemes, but there are other color schemes that need to be implemented.
You can find the HSL colors here https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/themes.ts

The missing color scheme are:
- [ ] Stone @hamza-imran75 
- [ ] Gray
- [ ] Neutral
- [ ] Red
- [ ] Rose
- [ ] Orange
- [ ] Green
- [ ] Blue
- [ ] Yellow
- [ ] Violet

Both the __dark__ and __light__ mode of each color scheme need to be implemented.
> If you want to contribute, please __comment__ with the color scheme you're going to implement, and I'll edit this post putting your nickname, so other users will not start the same color scheme.

## Instructions

1. Get the HSL from https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/themes.ts
2. To convert from shadcn to the Material `Color` you can do:
  ```css
  foreground: "240 10% 3.9%"
  ```
  ```dart
  print('foreground: ${HSLColor.fromAHSL(1, 240, 0.10, 0.039).toColor()}');
  ```
3. Set the obtained color in your `lib/src/theme/color_scheme/NAME.dart` where `NAME` is your color scheme name.
  > You can duplicate `slate.dart` and just change the file name, and the colors

**Comment by hamza-imran75** [comment]
I'll like to do stone 👋🏼

**Comment by dickermoshe** [comment]
I spent some time writing a script for this, but it seems that I cannot get my output for zinc to match what's already there.
I'll try again later, but it seems that the current zinc may not be correctly translated,

**Comment by nank1ro** [comment]
> I spent some time writing a script for this, but it seems that I cannot get my output for zinc to match what's already there.
> 
> I'll try again later, but it seems that the current zinc may not be correctly translated, 

I did them quickly, I might have made a mistake

**Comment by dickermoshe** [comment]
@hamza-imran75 
I automated it all, I feel bad if you wasted time on this.

**Comment by hamza-imran75** [comment]
@dickermoshe nah it's alright I was busy all day so didn't even get chance to get started 😅
